src/main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("my_app.urls"))
]

src/my_app/urls.py
from django.urls import path
from .views import test_view, redirect_view

app_name = 'app'

urlpatterns = [
    path("", test_view, name='test'),
    path("<str:new_link>/", redirect_view, name='redir')
]

src/my_app/models.py
import random
import string
from django.db import models


# Create your models here.

class Links(models.Model):
    old_link = models.URLField()
    new_linl = models.URLField()
    
    def save(self, *args, **kwargs):
        if not self.new_linl:
            self.new_linl = self.get_url()
        super(Links, self).save(*args, **kwargs)

    def get_url(self):
        current_codes = list(Links.objects.values_list(
            'new_linl', flat=True))
        while True:
            new_linl = self.gen_url()
            if new_linl not in current_codes:
                break
            else:
                continue
        return new_linl

    
    @staticmethod
    def gen_url():
        url = ''
        for i in range(4):
            url += random.choice(string.ascii_lowercase)
        return url

src/my_app/forms.py
from django import forms

class LinkForm(forms.Form):
    link = forms.URLField()
    link.widget.attrs.update({
        'class': 'form-control', 
        'placeholder': "Please enter link"})

src/my_app/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import LinkForm
from .models import Links

# Create your views here.


def test_view(request):
    if request.method == 'POST':
        if not Links.objects.filter(old_link=request.POST['link']):
            Links.objects.create(
                old_link=request.POST['link'])
    form = LinkForm()
    links = Links.objects.all().order_by("-id")
    return render(request, "my_app/test.html", context={"form":form, "links":links })

def redirect_view(request, new_link):
    link = Links.objects.filter(new_linl=new_link).last()
    return HttpResponseRedirect(link.old_link)

src/my_app/templates/my_app/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <title></title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </div>
      </nav>
      <div class="d-flex justify-content-center align-items-center container">

        <form class="w-25 p-3" action={% url 'app:test' %} method="POST">
                {% csrf_token %}
                {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
        </div>
        {% for link in links%}
        <div class="d-flex justify-content-center align-items-center container">
          <div class="card" style="width: 18rem;">
              <div class="card-body">
                <a =target="_blank" href="{% url 'app:redir' new_link=link.new_linl  %}" class="card-link">{{ link.new_linl }}</a><br>
            </div>
          </div>
        </div><br>
        {% endfor %}
    
</body>
</html>
    